

# GENERAL OPTIONS 
# ===============

# Exploration options
LAZY_SOLVES = False

# Solver options
CACHE_COMMON_CONSTRAINTS = False

# Debugging options
SIMGRVIZ = False

# STATE OPTIONS
# ==============
STATE_STOP_AT_ADDCONSTRAINT = "STATE_STOP_AT_ADDCONSTRAINT" 


# SOLVER OPTIONS
# ==============
SOLVER_BITWUZLA = "BITWUZLA"
SOLVER_YICES2 = "YICES2"
SOLVER_Z3 = "Z3"
SOLVER_BOOLECTOR = "BOOLECTOR"

# Default is Bitwuzla 
SOLVER = SOLVER_YICES2